### ISSUE TITLE
npm install with v7.13.0 fails

### ISSUE THREAD

**Issue by mraible** [dalexandrov/generator-jhipster-helidon#2]
I tried cloning this project and running `npm install` with npm v7.13.0. It fails.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for each-async@^0.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by dalexandrov** [comment]
Yep, but since I'm not a npm expert, I kindly ask for help here.
I now use `jhipster-helidon` for generation

**Comment by mraible** [comment]
I don't see `each-async` on [npmjs.com](https://www.npmjs.com/search?q=each-async), which might mean it only exists in your local repo. Maybe try removing it from your `package.json`? https://github.com/dalexandrov/generator-jhipster-helidon/blob/main/package.json#L30

If I remove it and try again, I get:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2021-05-18T14_40_10_771Z-debug.log
```

I upgraded npm using `npm i -g npm` and tried again. This time it worked and I ran `npm link` to try it out.

I created a new `helidon` directory, cd'd into it, and ran:

```
jhipster --blueprints helidon
```

After entering in my base name, it errored out.

```
? What is the base name of your application? helidon
ERROR! SQL_DB_OPTIONS is not defined
ReferenceError: SQL_DB_OPTIONS is not defined
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster-helidon/generators/generator-helidon-constants.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster-helidon/generators/server/index.js:7:29)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Unhandled promise rejection at:
ReferenceError: SQL_DB_OPTIONS is not defined
```

**Comment by dalexandrov** [comment]
Thank you! It was a typo)

But, if I apply your fix, I've got:

```
ERROR! jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/Users/mitia/Desktop/generator-jhipster-helidon/generators/server/index.js:22:19)
    at Environment.instantiate (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:748:23)
    at instantiate (/Users/mitia/Desktop/generator-jhipster-helidon/node_modules/yeoman-generator/lib/index.js:1196:23)
    at module.exports.composeWith (/Users/mitia/Desktop/generator-jhipster-helidon/node_modules/yeoman-generator/lib/index.js:1227:33)
    at module.exports.composeServer (/Users/mitia/Desktop/generator-jhipster-helidon/generators/app/index.js:102:22)
    at Object.<anonymous> (/Users/mitia/Desktop/generator-jhipster-helidon/node_modules/yeoman-generator/lib/index.js:976:25)
    at /Users/mitia/Desktop/generator-jhipster-helidon/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/mitia/Desktop/generator-jhipster-helidon/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/mitia/Desktop/generator-jhipster-helidon/node_modules/yeoman-generator/lib/index.js:977:11)
Unhandled promise rejection at:
TypeError: jhContext.setupServerOptions is not a function
```

**Comment by mraible** [comment]
@mshima Any ideas?

**Comment by mshima** [comment]
`setupServerOptions` was removed at JHipster 7.
Probably this blueprint was generated using released generator-jhipster-blueprint.
We should release a new version updating to jhipster 7.

If removing setupServerOptions doesn’t fix. I can take a deeper look later

**Comment by dalexandrov** [comment]
Thank you @mshima!
This helped, but now i have this warning:

```? What is the base name of your application? ttt
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, PostgreSQL, Oracle)
? Which *production* database would you like to use? MySQL
? Do you want to use Hibernate 2nd level cache? No
? Would you like to use Maven for building the backend? Maven
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? Which *Framework* would you like to use for the client? No client
WARNING! Deprecated: JHipster seems to be invoked using Yeoman command. Please use the JHipster CLI. Run jhipster <command> instead of yo jhipster:<command>
? Would you like to enable internationalization support? No```

**Comment by dalexandrov** [comment]
@mraible @mshima ?

**Comment by mshima** [comment]
I suggest to drop constructor from every generator.
You are trying to replace the entire workflow.
https://github.com/dalexandrov/generator-jhipster-helidon/blob/b2cbcd15e2250742a3496670f553210864186a89/generators/app/index.js#L97-L130

You should try to simplify the workflow and add missing priorities.
